[MIPS] Fix ToBooleanStub to return result in v0.
This is modeled after Daniel's original commit a22e19e7, however,
this is applied to an older version of ToBooleanStub.

This fixes errors with the pattern:

     TypeError: Cannot read property 'length' of null